# Happy path test
PUT http://localhost:9000/content
Content-Type: application/json

{
  "title": "Fairy-tale",
  "username": "Astrid L.",
  "date": "2020-05-11",
  "text": "lorem ipsum dolor sit amet"
}

###

# Happy path test
GET http://localhost:9000/contents

###

# Happy path test
PUT http://localhost:9000/login
Content-Type: application/json

{
  "username": "bob",
  "password": "123"
}

###

# Wrong endpoint data for test
PUT http://localhost:9000/login
Content-Type: application/json

{
  "username": "bob"
}

###

# Happy path test
PUT http://localhost:9000/register
Content-Type: application/json

{
  "username": "rob",
  "fullname": "Robert Henrikson",
  "phoneNumber": "123-123-123",
  "password": "456"
}

###

# Wrong endpoint data for test
PUT http://localhost:9000/register
Content-Type: application/json

{
  "username": "rob",
  "fullname": "Robert Henrikson",
  "phoneNumber": "123-123-123"
}

###